### ISSUE TITLE
Add cloud credential ccoctl to user's path

### ISSUE THREAD

**Issue by bparry02** [dmc5179/quay-image-builder#16]
Extract the ccoctl and make available to be executed on the registry host:
https://docs.openshift.com/container-platform/4.10/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#cco-ccoctl-configuring_cco-mode-sts

**Comment by dmc5179** [comment]
Fixed here: https://github.com/dmc5179/quay-image-builder/commit/871a9bd9c501af73b251065e2cb70139987d6a09
