### ISSUE TITLE
Create lvm logical volume for /opt/quay

### ISSUE THREAD

**Issue by bparry02** [dmc5179/quay-image-builder#9]
If a user wants to upgrade the cluster, they will need to copy image content from one or more releases to an existing registry. As part of the image build, create a logical volume that can be easily expanded to host `/opt/quay` image content.

**Comment by dmc5179** [comment]
definitely not creating logical volumes for AWS instances. LVMs in AWS is awful. Simply use another EBS storage device. You can do everything with another EBS device that LVM can do except much faster and easier.

**Comment by bparry02** [comment]
Yes, we'll close this and we can just document the steps for expanding the EBS volume.
